### ISSUE TITLE
Reduce example in docs doesn't work because `f` namespace shortcut doesn't always work

### ISSUE THREAD

**Issue by MarcoWorms** [grrr-amsterdam/garp-functional#6]
So, this is a really cool issue. If we get the reduce example:

```php
$sum = f\reduce('f\add', 0, $numbers); // 90
```

this will explode:

```
PHP Warning:  array_reduce() expects parameter 2 to be a valid callback, function 'f\add' not found or invalid function name in /home/worms/Documents/phpplayground/vendor/grrr-amsterdam/garp-functional/library/Garp/Functional/Reduce.php on line 21
```

and that happens because PHP doesn't translate 'f\' inside the string to 'Garp\Functional\'. You either have to send the whole namespace:

```php
$sum = f\reduce('Garp\Functional\add', 0, $numbers); // 90
```

Or do a nifty ugly little workaround like I did:

```php
$f = 'Garp\Functional\\';
$sum = f\reduce($f.'add', 0, $numbers); // 90
```

So this opens up 2 issues:

1. (Solved in PR: https://github.com/grrr-amsterdam/garp-functional/pull/5) We need to fix the docs example because it doesn't work and may cause confusion.

2. Is there a better way to send functions inside renamed namespaces as parameters?

**Comment by harmenjanssen** [comment]
That is a good point and one I've encountered in the wild a lot.  
Honestly, things like these are why I vastly prefer Javascript over PHP, because there you can just reference a function by name, making everything a lot more expressive.

The fact that all these can reference something `callable` is just plain confusing:

```php
"strtolower";
["Class", "method"];
$functionVariable;
```

But that doesn't really solve our problem. :)
For some functions I've chosen to curry them all the way down to zero arguments.

That way you could do something like this:

```php
$sum = f\reduce(f\add(), 0, $numbers);
```

But that's not a great solution either.  
I actually think your nifty ugly solution is not bad. Maybe omit the last backslash to mimic how you would write it if PHP _would_ resolve the namespace correctly:

```php
use Garp\Functional as f;
$f = "Garp\Functional";

$sum = f\reduce("$f\\add", 0, $numbers);
```

It's a shame we have to escape the backslash.

**Comment by MarcoWorms** [comment]
Yep, JS is ❤️, but it's ok we can survive with the workarounds :)

The curry solution is also good but like you said sometimes it won't work :P
